const TRANSACTION_TYPES = {
  CREATE_CONTACT: "CREATE_CONTACT"
}

const TRANSACTION_STATUS_TYPES = {
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  PENDING: "PENDING"
}

export default { TRANSACTION_TYPES, TRANSACTION_STATUS_TYPES }