const TRANSACTION_TYPES = {
  CREATE_CONTACT: "CREATE_CONTACT"
}

const TRANSACTION_STATUS_TYPES = {
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  PENDING: "PENDING"
}

const TRANSACTION_NAMES = {
  UPDATE_CONTACT: "UPDATE_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT"
}

export { TRANSACTION_TYPES, TRANSACTION_STATUS_TYPES, TRANSACTION_NAMES }